# Generated by Django 4.2.6 on 2023-10-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapps2023', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='common_name',
            field=models.CharField(max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='gic_decision',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='last_assessment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='legal_common_name',
            field=models.CharField(max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='legal_population',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='listed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='location',
            field=models.CharField(max_length=227, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='population',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='sara_schedule',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='schedule_status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='scientific_name',
            field=models.CharField(max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='taxonomic_group',
            field=models.CharField(max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='under_consideration_for',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
