# Generated by Django 4.2.6 on 2023-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceapps2023', '0002_alter_animals_common_name_alter_animals_gic_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('flag_marqueur', models.CharField(max_length=1)),
                ('value_valeur', models.DecimalField(decimal_places=4, max_digits=7)),
                ('sdl_lde', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mdl_ldm', models.IntegerField()),
                ('vmv_code', models.IntegerField()),
                ('unit', models.CharField(max_length=8)),
                ('variable', models.CharField(max_length=31)),
                ('variable_fr', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=1)),
                ('sample_id_chantillon', models.CharField(max_length=12)),
            ],
        ),
    ]
